#!/usr/bin/env node
/*
 * Scans vj/works/ for work pages and regenerates vj/works/works-list.js, which
 * defines window.VJ_WORKS for vj-control.html.
 *
 * Run after adding/removing/renaming a work:
 *   node vj/build-works.js
 *
 * Rules:
 *   - Includes works/<name>.html
 *   - Skips files starting with "_" (e.g. _template.html) and works-list.js
 *   - Label = the work's protocol "badge" if present, else Title Case of the file name
 */

const fs = require("fs");
const path = require("path");

const worksDir = path.join(__dirname, "works");
const outFile = path.join(worksDir, "works-list.js");

function titleCase(name) {
  return name
    .split(/[-_]/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function readBadge(filePath) {
  try {
    const html = fs.readFileSync(filePath, "utf8").replace(/<!--[\s\S]*?-->/g, "");
    const match = html.match(/<script id="vj-layer-protocol"[^>]*>([\s\S]*?)<\/script>/);
    if (!match) return null;
    const protocol = JSON.parse(match[1]);
    return typeof protocol.badge === "string" && protocol.badge.trim() ? protocol.badge.trim() : null;
  } catch (error) {
    console.warn(`! Could not read protocol from ${path.basename(filePath)}: ${error.message}`);
    return null;
  }
}

const files = fs
  .readdirSync(worksDir)
  .filter((name) => name.endsWith(".html") && !name.startsWith("_"))
  .sort();

const works = files.map((name) => {
  const base = name.replace(/\.html$/, "");
  return {
    src: `works/${name}`,
    label: readBadge(path.join(worksDir, name)) || titleCase(base)
  };
});

const banner = "// AUTO-GENERATED by vj/build-works.js — do not edit by hand.\n" +
  "// Regenerate with: node vj/build-works.js\n";
const body = `window.VJ_WORKS = ${JSON.stringify(works, null, 2)};\n`;
fs.writeFileSync(outFile, banner + body);

console.log(`Wrote ${path.relative(process.cwd(), outFile)} with ${works.length} work(s):`);
works.forEach((work) => console.log(`  - ${work.src}  (${work.label})`));
