// AUTO-GENERATED by vj/build-works.js — do not edit by hand.
// Regenerate with: node vj/build-works.js
window.VJ_WORKS = [
  {
    "src": "works/line-tunnel.html",
    "label": "Line tunnel"
  },
  {
    "src": "works/plasma-bloom.html",
    "label": "Plasma bloom"
  }
];
