// AUTO-GENERATED by vj/build-works.js — do not edit by hand.
// Regenerate with: node vj/build-works.js
window.VJ_WORKS = [
  {
    "src": "works/aurora.html",
    "label": "Aurora"
  },
  {
    "src": "works/bars.html",
    "label": "Bars"
  },
  {
    "src": "works/boids.html",
    "label": "Boids"
  },
  {
    "src": "works/bokeh.html",
    "label": "Bokeh"
  },
  {
    "src": "works/bolt.html",
    "label": "Bolt"
  },
  {
    "src": "works/caustics.html",
    "label": "Caustics"
  },
  {
    "src": "works/checker.html",
    "label": "Checker"
  },
  {
    "src": "works/contours.html",
    "label": "Contours"
  },
  {
    "src": "works/corridor.html",
    "label": "Corridor"
  },
  {
    "src": "works/drift.html",
    "label": "Drift"
  },
  {
    "src": "works/feedback.html",
    "label": "Feedback"
  },
  {
    "src": "works/flow.html",
    "label": "Flow"
  },
  {
    "src": "works/halftone.html",
    "label": "Halftone"
  },
  {
    "src": "works/helix.html",
    "label": "Helix"
  },
  {
    "src": "works/hex.html",
    "label": "Hex"
  },
  {
    "src": "works/kaleido.html",
    "label": "Kaleido"
  },
  {
    "src": "works/line-tunnel.html",
    "label": "Line tunnel"
  },
  {
    "src": "works/lissajous.html",
    "label": "Lissajous"
  },
  {
    "src": "works/mandala.html",
    "label": "Mandala"
  },
  {
    "src": "works/moire.html",
    "label": "Moiré"
  },
  {
    "src": "works/mono-grid.html",
    "label": "Grid"
  },
  {
    "src": "works/nebula.html",
    "label": "Nebula"
  },
  {
    "src": "works/noise.html",
    "label": "Noise"
  },
  {
    "src": "works/orbits.html",
    "label": "Orbits"
  },
  {
    "src": "works/plasma-bloom.html",
    "label": "Plasma bloom"
  },
  {
    "src": "works/plasma.html",
    "label": "Plasma"
  },
  {
    "src": "works/rays.html",
    "label": "Rays"
  },
  {
    "src": "works/rings.html",
    "label": "Rings"
  },
  {
    "src": "works/ripples.html",
    "label": "Ripples"
  },
  {
    "src": "works/seeds.html",
    "label": "Seeds"
  },
  {
    "src": "works/spiral.html",
    "label": "Spiral"
  },
  {
    "src": "works/starfield.html",
    "label": "Starfield"
  },
  {
    "src": "works/strobe.html",
    "label": "Strobe"
  },
  {
    "src": "works/sweep-lines.html",
    "label": "Sweep"
  },
  {
    "src": "works/truchet.html",
    "label": "Truchet"
  },
  {
    "src": "works/voronoi.html",
    "label": "Voronoi"
  },
  {
    "src": "works/warp-tunnel.html",
    "label": "Tunnel"
  },
  {
    "src": "works/wave-grid.html",
    "label": "Wave grid"
  },
  {
    "src": "works/waveform.html",
    "label": "Waveform"
  },
  {
    "src": "works/wipe.html",
    "label": "Wipe"
  },
  {
    "src": "works/wireframe.html",
    "label": "Wireframe"
  }
];
